Amax.Referral.Web/Controllers/ReferenceReportController.cs
using Amax.Referral.Web.Models;
using AmaxIns.DataContract.Referral;
using AmaxIns.DataContract.Referral.Token;
using AmaxIns.ServiceContract.Agency;
using AmaxIns.ServiceContract.Referral;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using X.PagedList;

namespace Amax.Referral.Web.Controllers
{
    [Authorize]
    public class ReferenceReportController : Controller
    {
        IReferralService referralService;
        IConfiguration config;
        IAgencyService agencyService;
        IAgencyLoginService _agencyLogin;
        public ReferenceReportController(IReferralService _referralService, IConfiguration _config, IAgencyService _agencyService, IAgencyLoginService agencyLogin)
        {
            referralService = _referralService;
            config = _config;
            agencyService = _agencyService;
            _agencyLogin = agencyLogin;
        }
        public IActionResult Index(int? page, int month, int year, string type)
        {
            var ShowTouchReport = config.GetSection("ShowTouchReport").Value;
            ViewBag.ShowTouchReport = ShowTouchReport;
            string zip = "";
            int agencyId = 0;
            try
            {
                AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
                TokenModel token = new TokenModel();
                token.AgentId = Convert.ToInt32(userdata.AgentId);
                token.Token = userdata.Token;
                if (!_agencyLogin.ValidateToken(token))
                {
                    return RedirectToAction("Logout", "Authentication");
                }
                zip = userdata.Zip;
                agencyId = userdata.AgencyId;
            }
            catch
            {

            }

            if (month == 0)
            {
                month = DateTime.Now.Month;
            }
            if(year == 0)
            {
                year = DateTime.Now.Year;
            }
            if (type == null)
            {
                type = ReferedBy.Agent.ToString();
            }
            var result = referralService.ReferralReport(month, year, type, zip, agencyId);
            ViewBag.type = type;
            ViewBag.IsAdmin = agencyId == -1 ? true : false;
            ViewBag.month = month;
            ViewBag.year = year;
            var pageNumber = page ?? 1;
            var PageSize = config.GetSection("PageSize").Value;
            var data = result.ToPagedList(pageNumber, Convert.ToInt32(PageSize));
            ViewBag.Months = Utility.Utility.GetMonthSelectList();
            ViewBag.Years = Utility.Utility.GetYearSelectList();
            return View(data);

        }

        public IActionResult CommentBox(int refid)
        {
            AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
            TokenModel token = new TokenModel();
            token.AgentId = Convert.ToInt32(userdata.AgentId);
            token.Token = userdata.Token;
            if (!_agencyLogin.ValidateToken(token))
            {
                return RedirectToAction("Logout", "Authentication");
            }
            IEnumerable<CommentsModel> comments = new List<CommentsModel>();
            comments = referralService.GetComments(refid);
            var model = new CommentsModel();
            model.ReferenceId = refid;
            model.AgencyId = userdata.AgencyId;
            ViewBag.CommentList = comments;
            return View(model);
        }

        public IActionResult SaveComment(CommentsModel model)
        {
            AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
            TokenModel token = new TokenModel();
            token.AgentId = Convert.ToInt32(userdata.AgentId);
            token.Token = userdata.Token;
            if (!_agencyLogin.ValidateToken(token))
            {
                return RedirectToAction("Logout", "Authentication");
            }
            if (!string.IsNullOrWhiteSpace(model.Comments))
            {
                referralService.Addcomments(model);
                return Json("success");
            }
            return Json("error");


        }


        public IActionResult ExportToCSV(int month, int year)
        {
            string zip = "";
            int agencyId = 0; ;
            try
            {
                AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
                TokenModel token = new TokenModel();
                token.AgentId = Convert.ToInt32(userdata.AgentId);
                token.Token = userdata.Token;
                if (!_agencyLogin.ValidateToken(token))
                {
                    return RedirectToAction("Logout", "Authentication");
                }
                zip = userdata.Zip;
                agencyId = userdata.AgencyId;
            }
            catch
            {

            }
            var result = referralService.ReferralReport(month, year, "", zip, agencyId);
            var agencies = agencyService.Get().Result.ToList();
            agencies.Add(new AmaxIns.DataContract.Agency.AgencyModel { AgencyId = 99, AgencyName = "Haltom City" });
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("Referral ID ,Customer Name,Customer Email,Customer Phone,Zip Code,Referral Name,Referral Email,Referral Phone,Year,Month,Agent ID,Agency ID,Agency Name,Converted to Sale,Entry Date,Routed to,Comment");
            foreach (var x in result)
            {
                string agencyName = string.Empty;
                string RouteToAgencyName = string.Empty;
                if (!string.IsNullOrWhiteSpace(x.AgencyID))
                {
                    var agencyData = agencies.Where(m => m.AgencyId.ToString() == x.AgencyID).FirstOrDefault();
                    if(agencyData != null)
                    {
                        agencyName = agencyData.AgencyName;
                    }
                }

                if (!string.IsNullOrWhiteSpace(x.RoutedTo))
                {
                    var RouteToAgencyData = agencies.Where(m => m.AgencyId.ToString() == x.RoutedTo).FirstOrDefault();
                    if (RouteToAgencyData != null)
                    {
                        RouteToAgencyName = RouteToAgencyData.AgencyName;
                    }
                }

                sb.AppendLine(x.referrelId + "," + x.UserName + "," + x.UserEmail + "," + x.UserPhone + "," + x.ZipCode + "," + x.ReferralName + "," + x.ReferralEmail + "," + x.ReferralPhone + "," + x.Year + "," + x.MonthName + "," + x.AgentId + "," + x.AgencyID + "," + agencyName + "," + (x.IsCustomer ? "Yes" : "No") + "," + x.CreatedDate.ToShortDateString() + "," + RouteToAgencyName + "," + x.Comment);
            }


            byte[] bytes = Encoding.ASCII.GetBytes(sb.ToString());
            //var Fileresult = new FileContentResult(bytes, "application/octet-stream");
            //Fileresult.FileDownloadName = "Reports.csv";
            return File(bytes, "application/octet-stream", "Reports.csv"); // Fileresult;
        }

        public IActionResult ExportUntouchedOrTouchedToCSV(int month, int year, string type)
        {
            AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
            TokenModel token = new TokenModel();
            token.AgentId = Convert.ToInt32(userdata.AgentId);
            token.Token = userdata.Token;
            if (!_agencyLogin.ValidateToken(token))
            {
                return RedirectToAction("Logout", "Authentication");
            }
            bool seachType = type == "touched" ? true : false;
            string filename = type == "touched" ? "TouchedQuotes.csv" : "UntouchedQuotes.csv";
            var result = referralService.ReferralTouchedUnTouchedReport(month, seachType);
            var agencies = agencyService.Get().Result.ToList();
            agencies.Add(new AmaxIns.DataContract.Agency.AgencyModel { AgencyId = 99, AgencyName = "Haltom City" });
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("Referral ID ,Customer Name,Customer Email,Customer Phone,Zip Code,Referral Name,Referral Email,Referral Phone,Year,Month,Agent ID,Agency ID,Agency Name,Converted to Sale,Entry Date,Routed to");
            foreach (var x in result)
            {
                string agencyName = string.Empty;
                string RouteToAgencyName = string.Empty;
                if (!string.IsNullOrWhiteSpace(x.AgencyID))
                {
                    var agencyData = agencies.Where(m => m.AgencyId.ToString() == x.AgencyID).FirstOrDefault();
                    if (agencyData != null)
                    {
                        agencyName = agencyData.AgencyName;
                    }
                }

                if (!string.IsNullOrWhiteSpace(x.RoutedTo))
                {
                    var RouteToAgencyData = agencies.Where(m => m.AgencyId.ToString() == x.RoutedTo).FirstOrDefault();
                    if (RouteToAgencyData != null)
                    {
                        RouteToAgencyName = RouteToAgencyData.AgencyName;
                    }
                }

Amax.Referral.Web/Controllers/TurboratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Amax.Referral.Web.Models;
using AmaxIns.DataContract.Referral;
using AmaxIns.DataContract.Referral.Token;
using AmaxIns.DataContract.Referral.Turborator;
using AmaxIns.ServiceContract.Agency;
using AmaxIns.ServiceContract.Referral;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using X.PagedList;

namespace Amax.Referral.Web.Controllers
{
    [Authorize]
    public class TurboratorController : Controller
    {
        IConfiguration _config;
        IAgencyService _agencyService;
        ITurboratorService _turboratorService;
        IReferralService _referralService;
        IAgencyLoginService _agencyLogin;
        public TurboratorController(ITurboratorService turboratorService, IConfiguration config, IAgencyService agencyService, IReferralService referralService, IAgencyLoginService agencyLogin)
        {
           _turboratorService = turboratorService;
            _config = config;
            _agencyService = agencyService;
            _referralService = referralService;
            _agencyLogin = agencyLogin;
        }

        public IActionResult Index(int? page, int month, int year)
        {

            int agencyId = 0; ;
            try
            {
                AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
                TokenModel token = new TokenModel();
                token.AgentId = Convert.ToInt32(userdata.AgentId);
                token.Token = userdata.Token;
                if (!_agencyLogin.ValidateToken(token))
                {
                    return RedirectToAction("Logout", "Authentication");
                }
                // zip = userdata.Zip;
                agencyId = userdata.AgencyId;
            }
            catch
            {

            }
            if (month == 0)
            {
                month = DateTime.Now.Month;
            }

            if (year == 0)
            {
                year = DateTime.Now.Year;
            }
            var result = _turboratorService.TurboratorReferralReport(month, year, agencyId);
            
            var pageNumber = page ?? 1;
            var PageSize = _config.GetSection("PageSize").Value;
            var data = result.ToPagedList(pageNumber, Convert.ToInt32(PageSize));
            ViewBag.IsAdmin = agencyId == -1 ? true : false;
            ViewBag.month = month;
            ViewBag.year = year;
            ViewBag.Months = Utility.Utility.GetMonthSelectList();
            ViewBag.Years = Utility.Utility.GetYearSelectList();
            return View(data);

        }

        public IActionResult TurboraterCommentBox(int id)
        {
            AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
            TokenModel token = new TokenModel();
            token.AgentId = Convert.ToInt32(userdata.AgentId);
            token.Token = userdata.Token;
            if (!_agencyLogin.ValidateToken(token))
            {
                return RedirectToAction("Logout", "Authentication");
            }
            IEnumerable<CommentsModel> comments = new List<CommentsModel>();
            comments = _referralService.GetTurboratorComments(id);
            var model = new CommentsModel();
            model.ReferenceId = id;
            model.AgencyId = userdata.AgencyId;
            ViewBag.CommentList = comments;
            return View(model);
        }

        public IActionResult SaveComment(CommentsModel model)
        {
            AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
            TokenModel token = new TokenModel();
            token.AgentId = Convert.ToInt32(userdata.AgentId);
            token.Token = userdata.Token;
            if (!_agencyLogin.ValidateToken(token))
            {
                return RedirectToAction("Logout", "Authentication");
            }
            if (!string.IsNullOrWhiteSpace(model.Comments))
            {
                _referralService.AddTurboratorcomments(model);
                return Json("success");
            }
            return Json("error");
       }

        public IActionResult ExportToCSV(int month, int year)
        {
            string zip = "";
            int agencyId = 0; ;
            try
            {
                AgencyLoginModel userdata = (AgencyLoginModel)JsonConvert.DeserializeObject(User.FindFirst(ClaimTypes.UserData).Value, typeof(AgencyLoginModel));
                TokenModel token = new TokenModel();
                token.AgentId = Convert.ToInt32(userdata.AgentId);
                token.Token = userdata.Token;
                if (!_agencyLogin.ValidateToken(token))
                {
                    return RedirectToAction("Logout", "Authentication");
                }
                zip = userdata.Zip;
                agencyId = userdata.AgencyId;
            }
            catch
            {
              
            }
            var result = _turboratorService.TurboratorReferralReport(month, year, agencyId);
            var agencies = _agencyService.Get().Result.ToList();
            agencies.Add(new AmaxIns.DataContract.Agency.AgencyModel { AgencyId = 99, AgencyName = "Haltom City" });
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("Location,Customer Name,Email,Phone,Zip Code,Converted to Sale,Comments");
            foreach (var x in result)
            {
                string agencyName = string.Empty;
                string RouteToAgencyName = string.Empty;
                if (x.Agencyid>0)
                {
                    var agencyData = agencies.Where(m => m.AgencyId == x.Agencyid).FirstOrDefault();
                    if (agencyData != null)
                    {
                        agencyName = agencyData.AgencyName;
                    }
                }
                
                sb.AppendLine(agencyName + "," + string.Concat(x.Name," ",x.Surname) + "," + x.Email + "," + x.PhoneNumber + "," + x.ZipCode + ","  + (x.ConvertedToCustomer ? "Yes" : "No") + "," + x.Comments );
            }


            byte[] bytes = Encoding.ASCII.GetBytes(sb.ToString());
            return File(bytes, "application/octet-stream", "Reports.csv"); // Fileresult;
        }
    }
}

Amax.Referral.Web/Views/Turborator/Index.cshtml
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@model IPagedList<AmaxIns.DataContract.Referral.Turborator.TurboratorModel>
@{
    Layout = "_LayoutSales";
}

    <meta http-equiv="refresh" content="900" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="~/lib/jquery.unobtrusive-ajax.min.js"></script>
@using (Html.BeginForm("Index", "Turborator", FormMethod.Post, new { @class = "reportsearchform" }))
{
    <div class="container-fluid">
        <div class="row searchbar mt-3">
            <div class="col-lg-3 col-md-4 col-sm-12">
                <div class="row align-items-center">
                    <div class="col-md-3 col-sm-12">
                        <span>Year:</span>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        @Html.DropDownList("year", ViewBag.Years as IEnumerable<SelectListItem>, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-12">
                <div class="row align-items-center">
                    <div class="col-md-3 col-sm-12">
                        <span>Month:</span>
                    </div>
                    <div class="col-md-9 col-sm-12">
                        @Html.DropDownList("month", ViewBag.Months as IEnumerable<SelectListItem>, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-5 col-sm-12">
                <div class="row align-items-center">
                    <div class="col-sm-12">
                        <input type="submit" class="btn btn-primary" value="Search" />
                        @if (Convert.ToBoolean(ViewBag.IsAdmin))
                        {
                            <a href="/Turborator/ExportToCSV?month=@ViewBag.month&year=@ViewBag.year" class="btn btn-primary">Export to CSV</a>
                        }
                    </div>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-12">
                <a class="btn btn-Logout" value="" style="float:right;" href="/Authentication/Logout">Log out</a>
            </div>
        </div>
        <div class="row " style="color:green;">
            <div class="col-sm-12">
                <h3 class="text-center">Records in green are sold records</h3>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table ref-reporttable">
                        <thead>
                            <tr>
                                <th scope="col">Location </th>
                                <th scope="col">Customer Name </th>
                                <th scope="col">Email </th>
                                <th scope="col">Phone </th>
                                <th scope="col">Zip Code </th>
                                <th scope="col">Quote Url</th>
                                <th scope="col">Tr Quote Url</th>
                                <th scope="col">Is Sold</th>
                                <th scope="col">Date</th>
                                <th scope="col">Comment</th>

                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.Count; i++)
                            {
                                string isSold = "No";
                                if (Model[i].ConvertedToCustomer)
                                {
                                    isSold = "Yes";
                                }
                                else
                                {
                                    isSold = "No";
                                }
                                <tr style="@(Model[i].ConvertedToCustomer?"color:green":"")">
                                    <td>@Model[i].AgencyName</td>
                                    <td> @Model[i].Name @Model[i].Surname</td>
                                    <td> @Model[i].Email</td>
                                    <td> @Model[i].PhoneNumber</td>
                                    <td> @Model[i].ZipCode</td>
                                    <td><a target="_blank" href="@Model[i].QuoteUrl">Quote Site</a></td>
                                    <td> <a target="_blank" href="@Model[i].TrQuoteUrl">Turborator</a></td>
                                    <td>@isSold</td>
                                    <td>@Model[i].CreatedDate.ToShortDateString()</td>
                                    <td> <input type="button" class="btn btn-primary" onclick="ShowModel(@Model[i].TurboratorID)" value="Comment" /> </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, ViewBag.type, ViewBag.month, ViewBag.year }), new X.PagedList.Mvc.Common.PagedListRenderOptions
        {
            LiElementClasses = new string[] { "page-item" },
            PageClasses = new string[] { "page-link" }
        })
    </div>
}

<script>
    function ShowModel(id) {
        $('#Error').hide();
        $.get('/Turborator/TurboraterCommentBox?id=' + id, function (data) {
            $('#dialog').html(data);
            $("#dialog").dialog({
                height: 550,
                width: 950,
                draggable: false,
                resizable: false,
                modal: true,
            });
        })
    }

    function CloseModel(e) {
        var response = e.responseJSON;
        if (response === 'success') {
            $("#dialog").dialog('close')
        }
        else {
            $('#Error').show();
        }
    }

    //function ExportToexcel() {
    //    var month = $('#month').val();
    //    $.get("/ReferenceReport/ExportToCSV?month=" + month, function (e) {
    //        alert(e);
    //        console.log(e);
    //    });
    //}
</script>
<script src="~/js/jquery.stickytableheaders.js"></script>
<script>
    // adding filler rows
    for (var i = 0; i < 3; i++) {
        $('tbody tr').clone().appendTo('table');
    }
    var offset = $('.navbar').height();
    $("html:not(.legacy) table").stickyTableHeaders({ fixedOffset: offset });
</script>

<div id="dialog" title="Enter Comments" style="display:none;">

</div>

Amax.Referral.Web/Views/Turborator/TurboraterCommentBox.cshtml
@model AmaxIns.DataContract.Referral.CommentsModel
@{
    Layout = null;
}
<div class="row">
    <div class="col-sm-8">
        <div class="table-responsive">
            <table class="table ref-reporttable">
                <thead>
                    <tr>
                        <th scope="col" width="20%">Agency</th>
                        <th scope="col" width="60%">Comment</th>
                        <th scope="col" width="20%">Date</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var x in ViewBag.CommentList as List<AmaxIns.DataContract.Referral.CommentsModel>)
                    {

                        <tr>
                            <td>
                                @if (x.AgencyId > 0)
                                {
                                    @x.AgencyName;
                                }
                                else
                                {
                                    @Html.Raw("Admin");
                                }
                            </td>
                            <td>@x.Comments</td>
                            <td>@Convert.ToDateTime(x.Date).ToShortDateString()</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-sm-4">
        <form data-ajax="true" data-ajax-complete="CloseModel" asp-action="SaveComment" asp-controller="Turborator" method="post" enctype="multipart/form-data">

            <div class="row">
                <div class="col-sm-12">
                    Enter Comment:
                </div>
                <div class="col-sm-12">
                    @Html.TextAreaFor(m => m.Comments, new { @class = "form-control", @style = "height:300px" })
                    <div id="Error" class="error" style="display:none;color:red;">
                       Please enter comment.
                    </div>
                    @Html.HiddenFor(m => m.AgencyId)
                    @Html.HiddenFor(m => m.ReferenceId)
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12 text-right m-2">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>
@*<form data-ajax="true" data-ajax-success="CloseModel()" asp-action="SaveComment" asp-controller="ReferenceReport" method="post" enctype="multipart/form-data">
        <div class="row m-5">
            <div class="col-sm-3">
                Comment
            </div>
            <div class="col-sm-9">
                @Html.TextAreaFor(m => m.Comments)
                @Html.HiddenFor(m => m.AgencyId)
                @Html.HiddenFor(m => m.ReferenceId)
            </div>
        </div>
        <div class="row">
            <input type="submit" value="Save" />
        </div>
    </form>*@