Amax.Referral.Web/Controllers/AuthenticationController.cs
using Amax.Referral.Web.Models;
using AmaxIns.DataContract.Referral.Token;
using AmaxIns.Service.Refferal;
using AmaxIns.ServiceContract.Referral;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Security.Claims;

namespace Amax.Referral.Web.Controllers
{
    public class AuthenticationController : Controller
    {
        IAgencyLoginService service;
        public AuthenticationController(IAgencyLoginService _service)
        {
            service = _service;
        }
        public IActionResult Index(bool isNotValidUser, bool isNotValidAgent)
        {
            ViewBag.isNotValidUser = isNotValidUser;
            ViewBag.isNotValidAgent = isNotValidAgent;
            return View(new AgencyLoginModel());
        }

        [HttpPost]
        public IActionResult Validate(AgencyLoginModel model)
        {
            AgencyLoginModel agencyData = new AgencyLoginModel();
            var authtoken = Guid.NewGuid().ToString();
            ClaimsIdentity identity = null;
            bool isAuthenticated = false;
            bool isNotValidUser = false;
            bool isNotValidAgent = false;
            var data =service.validateAgency(new AmaxIns.DataContract.Referral.AgencyLogin.AgencyLoginModel { AgencyLogin = model.AgencyLogin.Trim(), Password = model.Password.Trim() });
            if (!string.IsNullOrEmpty(model.AgentId))
            {
                var agentData = service.validateAgent(new AmaxIns.DataContract.Referral.AgencyLogin.AgentLoginModel { LoginAgentID = model.AgentId.Trim() });
                
                if(agentData == null)
                {
                    isNotValidAgent = true;
                }
            }
            if(data!=null)
            {
                agencyData.Token = authtoken;
                agencyData.AgencyId = data.AgencyId;
                agencyData.Zip = data.Zip;
                agencyData.AgentId = model.AgentId;
                agencyData.start = true;
                identity = new ClaimsIdentity(new[] {
                    new Claim(ClaimTypes.Name,data.AgencyLogin ),
                    new Claim(ClaimTypes.UserData,JsonConvert.SerializeObject(agencyData) )
                }, CookieAuthenticationDefaults.AuthenticationScheme);
                if (isNotValidAgent == false)
                {
                    isAuthenticated = true;
                }
            }
            else
            {
                isNotValidUser = true;
            }

            if (isAuthenticated)
            {
                if(!string.IsNullOrEmpty(model.AgentId))
                {
                    TokenModel token = new TokenModel();
                    token.AgentId = Convert.ToInt32(model.AgentId);
                    token.Token = authtoken;
                    service.UpdateToken(token);
                }
                var principal = new ClaimsPrincipal(identity);
                var login = HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                return RedirectToAction("Index", "ReferenceReport");
            }

            return RedirectToAction("Index", new { isNotValidUser, isNotValidAgent });
        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index");
        }
    }
}

Amax.Referral.Web/Views/Authentication/Index.cshtml
@model Amax.Referral.Web.Models.AgencyLoginModel
@{
    Layout = null;
}

<!Doctype html>
<html>

<head>
    <title>Login Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Custom fonts for this template-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300i,400,500,600,700,800,900" rel="stylesheet">
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <!-- Custom styles for this template-->

    <link rel="stylesheet" href="~/css/Login.css" />
</head>

<body>
    <div class="home-page">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="home-bg new_login_page h-100vh">
                        <div class="row justify-content-center v-center">
                            <div class="col-md-6 col-lg-5 col-sm-8">
                                <div class="logo-content">
                                    <div class="home-content">
                                        <div class="login-content d-block">
                                            <div class="heading text-center">
                                                <h2>Welcome</h2>
                                            </div>

                                            <div id="Titlediv" class="row" style="margin-top:100px;padding-bottom:80px;font-size:40px;color:white;">
                                                <div class="col-sm-6 text-center">
                                                    <div class="" onclick="ShowAdminLogin()">
                                                        <div class="image">
                                                            <i class="fas fa-user-tie mr-2"></i>
                                                        </div>
                                                        <div class="title text-center">
                                                            <h3>Admin</h3>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-6 text-center">
                                                    <div class="" onclick="ShowAgentLogin()">
                                                        <div class="image">
                                                            <i class="fas fa-user mr-2"></i>
                                                        </div>
                                                        <div class="title text-center">
                                                            <h3>Agent</h3>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="login-form" id="Admindiv">
                                                <div style="color:red;">
                                                    @if (ViewBag.isNotValidUser == true)
                                                    {
                                                        <p>Invalid username or password.</p>
                                                    }
                                                </div>
                                                <div style="color:red;">
                                                    @if (ViewBag.isNotValidAgent == true)
                                                    {
                                                        <p>Invalid Agent Id</p>
                                                    }
                                                </div>
                                                @using (Html.BeginForm("Validate", "Authentication", FormMethod.Post, new { @id = "AdminLoginForm" }))
                                                {
                                                    <div class="form-group">
                                                        <div class="icon-block">
                                                            @Html.TextBoxFor(m => m.AgencyLogin, new { @class = "form-control", @placeholder = "User Name" })

                                                        </div>
                                                        <span style="color:red;text-align:center">
                                                            @Html.ValidationMessageFor(m => m.AgencyLogin)
                                                        </span>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="icon-block">
                                                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                                                        </div>
                                                        <span style="color:red;text-align:center">
                                                            @Html.ValidationMessageFor(m => m.Password)
                                                        </span>
                                                    </div>

                                                    <div class="login-button text-center">
                                                        <button type="submit" class="login-btn">Login</button>
                                                    </div>
                                                    <div class="text-center" style="padding-bottom:20px;">
                                                        <a onclick="ShowTitlediv()"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
                                                    </div>
                                                }

                                            </div>

                                            <div class="login-form" id="Agentdiv">
                                                <div style="color:red;">
                                                    @if (ViewBag.isNotValidUser == true)
                                                    {
                                                        <p>Invalid username or password.</p>
                                                    }
                                                </div>
                                                <div style="color:red;">
                                                    @if (ViewBag.isNotValidAgent == true)
                                                    {
                                                        <p>Invalid Agent Id</p>
                                                    }
                                                </div>
                                                @using (Html.BeginForm("Validate", "Authentication", FormMethod.Post, new { @id = "AgentLoginForm" }))
                                                {
                                                    <div class="form-group">
                                                        <div class="icon-block">
                                                            @Html.TextBoxFor(m => m.AgencyLogin, new { @class = "form-control", @placeholder = "User Name" })

                                                        </div>
                                                        <span style="color:red;text-align:center">
                                                            @Html.ValidationMessageFor(m => m.AgencyLogin)
                                                        </span>
                                                    </div>
                                                    <div class="form-group">
                                                        <div class="icon-block">
                                                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                                                        </div>
                                                        <span style="color:red;text-align:center">
                                                            @Html.ValidationMessageFor(m => m.Password)
                                                        </span>
                                                    </div>

                                                    <div class="form-group">
                                                        <div class="icon-block">
                                                            @Html.TextBoxFor(m => m.AgentId, new { @class = "form-control", @placeholder = "Agent ID" })
                                                        </div>
                                                        <span style="color:red;text-align:center">
                                                            @Html.ValidationMessageFor(m => m.AgentId)
                                                        </span>

                                                        @*<span style="color:green;text-align:center">
                                                                <b>Enter Agent ID for Agent Login</b>
                                                            </span>*@
                                                    </div>

                                                    <div class="login-button text-center">
                                                        <button type="submit" class="login-btn">Login</button>
                                                    </div>
                                                    <div class="text-center" style="padding-bottom:20px;">
                                                        <a onclick="ShowTitlediv()"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script type='text/javascript'>
        $(document).ready(function () {
            $("#Admindiv").hide();
            $("#Agentdiv").hide();
        });

        function ShowAdminLogin() {
            $("#Admindiv").show();
            $("#Agentdiv").hide();
            $("#Titlediv").hide();
        }

        function ShowAgentLogin() {
            $("#Admindiv").hide();
            $("#Agentdiv").show();
            $("#Titlediv").hide();
        }

        function ShowTitlediv() {
            $("#Admindiv").hide();
            $("#Agentdiv").hide();
            $("#Titlediv").show();
        }
    </script>

</body>



</html>